# Generated by Django 5.0.1 on 2025-07-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_product_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title', 'size__order', 'color__name'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
